# Generated by Django 4.1.5 on 2023-02-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
