# Generated by Django 4.1.4 on 2023-02-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smokeShop', '0008_product_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
