# Generated by Django 4.1.4 on 2023-02-14 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smokeShop', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='smokeShop.product'),
            preserve_default=False,
        ),
    ]
