# Generated by Django 4.1.4 on 2023-02-17 19:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smokeShop', '0013_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_address_1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_country_area',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_country_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_first_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_last_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_phone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_postcode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='captured_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_ip_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fraud_message',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fraud_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='variant',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='smokeShop.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
