# Generated by Django 4.1.4 on 2023-02-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smokeShop', '0017_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
